import type { Metadata } from 'next';
import { LegalShell } from '../legal-shell';

export const metadata: Metadata = { title: 'Riscos de Uso — MU Login Manager', description: 'Entenda os riscos relacionados a automação, programas de terceiros e regras do MU Online Global.' };

export default function Riscos() {
  return <LegalShell eyebrow="RISCOS DE USO" title="Automação exige uma decisão informada." lead="Leia esta página antes de instalar ou utilizar o fluxo automático de login do MU Login Manager.">
    <section className="legal-highlight danger"><b>Não existe garantia contra banimento</b><p>O MU Login Manager é uma ferramenta independente. Ele não é afiliado, autorizado, certificado ou endossado pela Webzen. A administradora do jogo pode interpretar automações e programas de terceiros de acordo com seus próprios termos e políticas.</p></section>
    <section><h2>1. Risco relacionado às regras do jogo</h2><p>As políticas públicas do MU Online Global restringem programas automáticos, macros, ferramentas não oficiais e comportamentos considerados anormais. Embora o Manager tenha sido projetado para automatizar o fluxo de abertura e login — e não o combate ou ações dentro do mundo do jogo — não há uma exceção oficial conhecida que assegure que essa utilização seja permitida.</p><p>O uso pode, portanto, resultar em investigação, limitação, suspensão ou encerramento de contas, inclusive contas consideradas relacionadas, conforme a interpretação da Webzen.</p></section>
    <section><h2>2. O que o Manager se propõe a fazer</h2><ul><li>Abrir o launcher e o cliente;</li><li>Identificar telas e janelas;</li><li>Preencher credenciais armazenadas localmente;</li><li>Selecionar servidor e personagem configurados;</li><li>Registrar PID e janela para gerenciamento posterior.</li></ul><p>O produto não é apresentado como ferramenta para combate, farming, movimentação, habilidades, alteração de memória, injeção de código ou modificação dos arquivos do jogo.</p></section>
    <section><h2>3. Responsabilidade do usuário</h2><p>O usuário deve revisar as regras aplicáveis à sua conta, decidir se aceita o risco e interromper o uso caso não concorde. Uma assinatura do Manager não transfere ao desenvolvedor a responsabilidade por sanções decorrentes de decisões da administradora do jogo ou do uso simultâneo de outros programas.</p></section>
    <section><h2>4. Outros riscos</h2><div className="data-grid"><div><b>Conta e computador</b><p>Malware, acesso remoto, área de transferência comprometida ou outro usuário com acesso à sessão do Windows podem expor informações locais.</p></div><div><b>Automação visual</b><p>Mudanças no cliente, resolução, foco, latência ou proteção do jogo podem provocar cliques incorretos ou falha no login.</p></div><div><b>Disponibilidade</b><p>Serviços externos de licenciamento, pagamento, atualização e o próprio jogo podem ficar indisponíveis.</p></div><div><b>Instalador beta</b><p>Enquanto não houver assinatura digital comercial, o Windows pode exibir alertas de reputação. Baixe somente do projeto e confira o hash publicado.</p></div></div></section>
    <section><h2>5. Fontes oficiais</h2><p>Consulte diretamente a <a href="https://muonline.webzen.com/en/news/notices/announcement/35148/global-mu-online-operational-policy">Operational Policy do MU Online Global</a>, os <a href="https://www.webzen.com/legal/terms-of-service">Termos de Serviço da Webzen</a> e o <a href="https://cs.webzen.com/Inquiry/RegistInquiry">suporte oficial</a>. As regras podem mudar e prevalecem sobre qualquer explicação deste site.</p></section>
    <section><h2>6. Situação atual do projeto</h2><p>O projeto está em beta e pretende consultar formalmente a Webzen antes de ampliar sua distribuição. Até que exista uma resposta oficial, o risco de interpretação contrária permanece e deve ser considerado pelo usuário.</p></section>
  </LegalShell>;
}
