import type { Metadata } from 'next';
import { LegalShell } from '../legal-shell';

export const metadata: Metadata = { title: 'Política de Privacidade — MU Login Manager', description: 'Saiba quais informações o MU Login Manager utiliza, onde ficam armazenadas e quais serviços recebem dados.' };

export default function Privacidade() {
  return <LegalShell eyebrow="POLÍTICA DE PRIVACIDADE" title="Seus dados, sem letras miúdas." lead="Esta política explica o tratamento de informações na versão beta do MU Login Manager. Ela será revisada sempre que a arquitetura ou os fornecedores utilizados mudarem.">
    <section className="legal-highlight"><b>Resumo direto</b><p>Na versão atual, login e senha do jogo são armazenados no computador do usuário, protegidos pelo Windows DPAPI, e não são enviados aos serviços de pagamento, licenciamento ou atualização do MU Login Manager.</p></section>
    <section><h2>1. Informações armazenadas localmente</h2><p>As contas configuradas, incluindo login e senha do jogo, ficam em <code>%LOCALAPPDATA%\MU Login Manager\accounts.dat</code>. O conteúdo é protegido pelo Windows DPAPI e normalmente só pode ser descriptografado pelo mesmo usuário do Windows no mesmo ambiente.</p><p>Também podem ficar no computador configurações da automação, preferências, estado da licença, acompanhamento de compras e registros técnicos de execução.</p><div className="legal-warning"><b>Limite importante</b><p>Durante a automação, as credenciais precisam existir temporariamente na memória do processo e podem passar brevemente pela área de transferência para preencher o cliente. O Manager procura limpar esse conteúdo após o uso, mas nenhum programa local pode prometer proteção absoluta em um computador comprometido.</p></div></section>
    <section><h2>2. Informações transmitidas</h2><div className="data-grid"><div><b>Pagamentos</b><p>Plano, cupom, identificador da compra e CPF/CNPJ informado pelo comprador podem ser enviados ao serviço de billing e ao Asaas para criar, acompanhar e proteger a compra.</p></div><div><b>Licenciamento</b><p>Chave de licença, identificador derivado do computador, nome da máquina, sistema e estado de ativação podem ser enviados ao Keygen para validar limites e dispositivos.</p></div><div><b>Atualizações</b><p>O aplicativo consulta o GitHub Releases para verificar versões e baixar instaladores. O GitHub pode registrar informações técnicas da requisição conforme suas próprias políticas.</p></div><div><b>Credenciais do jogo</b><p>Login e senha do MU não integram os payloads previstos para pagamentos, licenciamento ou atualizações.</p></div></div></section>
    <section><h2>3. Finalidades</h2><ul><li>Executar o login solicitado pelo próprio usuário;</li><li>Salvar configurações e contas no dispositivo;</li><li>Validar licença, plano e limite de computadores;</li><li>Processar compras, avaliações, cupons e assinaturas;</li><li>Entregar atualizações e diagnosticar falhas técnicas.</li></ul></section>
    <section><h2>4. Fornecedores envolvidos</h2><p>O serviço utiliza Asaas para pagamentos, Keygen para licenciamento, Cloudflare para o backend de billing e GitHub para releases, site e suporte comunitário. Cada fornecedor pode tratar dados técnicos conforme sua própria política.</p></section>
    <section><h2>5. Retenção e exclusão</h2><p>Os arquivos locais permanecem até serem removidos pelo usuário ou pela própria aplicação. Registros de pagamento, prevenção a fraude e licenciamento podem ser mantidos pelo tempo necessário para cumprir obrigações legais, resolver disputas e impedir abuso de avaliações ou cupons.</p><p>Desinstalar o programa não necessariamente remove a pasta de dados locais nem registros que precisem ser preservados pelo serviço de pagamento.</p></section>
    <section><h2>6. Direitos e contato privado</h2><p>Solicitações relacionadas a acesso, correção ou exclusão de dados devem ser feitas sem publicar CPF, chaves, comprovantes ou credenciais em uma Issue. Para informações sensíveis, utilize o canal privado <a href="https://github.com/onezer00/mu-login-manager-site/security/advisories/new">Report a vulnerability</a> do repositório.</p></section>
    <section><h2>7. Mudanças nesta política</h2><p>Alterações relevantes serão publicadas nesta página com uma nova data de atualização. O uso de uma versão futura poderá exigir nova ciência quando o tratamento de dados mudar materialmente.</p></section>
  </LegalShell>;
}
